# Generated by Django 6.0.7 on 2026-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='geospatial/')),
                ('filename', models.CharField(max_length=255)),
                ('feature_count', models.IntegerField(default=0)),
                ('crs', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
