# Generated by Django 6.0.7 on 2026-10-07 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofile',
            name='measurement_crs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=20),
        ),
    ]
